---
title: "Generate Tidy Incidents Data"
author: "Pierre Monnot"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Generate Tidy Incidents Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r eval = FALSE}
library(readr)
library(dplyr)
library(stringr)
incidents <- read_csv("../data-raw/incidents.csv")

tidy_incidents <- incidents %>%
  select(IM_INCIDENT_KEY,
         FIRE_BOX,
         INCIDENT_TYPE_DESC,
         INCIDENT_DATE_TIME,
         ARRIVAL_DATE_TIME,
         LAST_UNIT_CLEARED_DATE_TIME,
         UNITS_ONSCENE,
         HIGHEST_LEVEL_DESC,
         ZIP_CODE,
         BOROUGH_DESC) %>%
  mutate(FIRE_BOX = case_when(BOROUGH_DESC == "1 - Manhattan" ~ paste0("M", FIRE_BOX),
                              BOROUGH_DESC == "2 - Bronx" ~ paste0("X", FIRE_BOX),
                              BOROUGH_DESC == "3 - Staten Island" ~ paste0("R", FIRE_BOX),
                              BOROUGH_DESC == "4 - Brooklyn" ~ paste0("B", FIRE_BOX),
                              BOROUGH_DESC == "5 - Queens" ~ paste0("Q", FIRE_BOX),
                              TRUE ~ FIRE_BOX)) %>%
  mutate(FIRE_BOX = factor(FIRE_BOX),
         INCIDENT_TYPE_DESC = factor(INCIDENT_TYPE_DESC),
         INCIDENT_DATE_TIME = as.POSIXct(INCIDENT_DATE_TIME),
         ARRIVAL_DATE_TIME = as.POSIXct(ARRIVAL_DATE_TIME),
         LAST_UNIT_CLEARED_DATE_TIME = as.POSIXct(LAST_UNIT_CLEARED_DATE_TIME),
         HIGHEST_LEVEL_DESC = factor(str_sub(HIGHEST_LEVEL_DESC, 1, 1), ordered = TRUE),
         ZIP_CODE = factor(ZIP_CODE),
         BOROUGH_DESC = factor(BOROUGH_DESC)) %>%
  rename(id = IM_INCIDENT_KEY,
         fire_box = FIRE_BOX,
         inc_type = INCIDENT_TYPE_DESC,
         inc_time = INCIDENT_DATE_TIME,
         arr_time = ARRIVAL_DATE_TIME,
         dep_time = LAST_UNIT_CLEARED_DATE_TIME,
         units = UNITS_ONSCENE,
         inc_level = HIGHEST_LEVEL_DESC,
         zip_code = ZIP_CODE,
         borough = BOROUGH_DESC)

devtools::use_data(tidy_incidents, tidy_incidents)
```

