---
title: "bm_exploration"
author: "benjamin Mai"
date: "19/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(readr)
library(tidyr)
```

## read

```{r}
data <- read.csv("../data-raw/incidents-responded-to-by-fire-companies.csv")
```

##study of the data

```{r}
summary(data)
dim(data)
names(data)
head(data)
View(data)
```

```{r}
#remove NA columns at the end
data <- data %>% select(1:17)
```


182 different types of issues
```{r}
#distinct issues
data %>% distinct(INCIDENT_TYPE_DESC)
```


```{r}
#evaluate number problems by issues
number_inter_by_issues <-  data %>% group_by(INCIDENT_TYPE_DESC) %>% 
  summarise(total = n()) %>% 
  arrange(desc(total))

nb_top20_inter <- sum(head(number_inter_by_issues, 20)$total)
nb_all_inter <- sum(number_inter_by_issues$total)

nb_top20_inter/nb_all_inter


```
we notice that 87.5% of all interventions concern only the top 20 biggest interventions (out of 182).


```{r}
data_by_year <- data %>% mutate(INCIDENT_DATE_TIME = substr(INCIDENT_DATE_TIME, 0, 4))
data_by_year

data_by_year %>% group_by(INCIDENT_DATE_TIME) %>% 
  summarise(total = n())
```
We notice that number of incidents seem quite stable over the 5 years with slightly lower incidents in 2013 and more in 2015. Why?? Influenced by what?? 
